#include <avr/io.h>
#include <avr/fuse.h>
#include <variant.h>

#if defined(AVR_AVRDU) || defined(AVR_AVREB)

FUSES = {
  .WDTCFG   = FUSE_WDTCFG_DEFAULT
, .BODCFG   = FUSE_BODCFG_DEFAULT
, .OSCCFG   = FUSE_OSCCFG_DEFAULT
, .SYSCFG0  = FUSE_SYSCFG0_DEFAULT | FUSE_RSTPINCFG | FUSE_UPDIPINCFG
, .SYSCFG1  = FUSE_SYSCFG1_DEFAULT
, .CODESIZE = FUSE_CODESIZE_DEFAULT
, .BOOTSIZE = FUSE_BOOTSIZE_DEFAULT
, .PDICFG   = FUSE_PDICFG_DEFAULT   /* DU and EB series only */
};

#elif defined(AVR_AVRDX) || defined(AVR_AVREX)

FUSES = {
  .WDTCFG   = FUSE_WDTCFG_DEFAULT
, .BODCFG   = FUSE_BODCFG_DEFAULT
, .OSCCFG   = FUSE_OSCCFG_DEFAULT
, .SYSCFG0  = FUSE_SYSCFG0_DEFAULT | FUSE_RSTPINCFG | FUSE_UPDIPINCFG
, .SYSCFG1  = FUSE_SYSCFG1_DEFAULT
, .CODESIZE = FUSE_CODESIZE_DEFAULT
, .BOOTSIZE = FUSE_BOOTSIZE_DEFAULT
};

#elif defined(AVR_TINYAVR)

FUSES = {
  .WDTCFG   = FUSE_WDTCFG_DEFAULT
, .BODCFG   = FUSE_BODCFG_DEFAULT
, .OSCCFG   = FUSE_OSCCFG_DEFAULT
, .SYSCFG0  = FUSE_SYSCFG0_DEFAULT | FUSE_RSTPINCFG0  /* enable UPDIPIN */
, .SYSCFG1  = FUSE_SYSCFG1_DEFAULT
, .APPEND   = FUSE_APPEND_DEFAULT
, .BOOTEND  = FUSE_BOOTEND_DEFAULT
};

#elif defined(AVR_MEGAAVR0)

FUSES = {
  .WDTCFG   = FUSE_WDTCFG_DEFAULT
, .BODCFG   = FUSE_BODCFG_DEFAULT
, .OSCCFG   = FUSE_OSCCFG_DEFAULT
, .SYSCFG0  = FUSE_SYSCFG0_DEFAULT | FUSE_RSTPINCFG
, .SYSCFG1  = FUSE_SYSCFG1_DEFAULT
, .APPEND   = FUSE_APPEND_DEFAULT
, .BOOTEND  = FUSE_BOOTEND_DEFAULT
};

#else
#error This MCU type is not supported
#include BUILD_STOP
#endif

// end of code
